version: '3.8'

services:
  web:
    build: .
    command: gunicorn -b 0.0.0.0:5000 manage:app
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    environment:
      - APP_SETTINGS=config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/resume_scanner
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: resume_scanner
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

